name: Publicar StudyBox no Neocities

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do projeto
        uses: actions/checkout@v4

      - name: Preparar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Instalar Neocities
        run: gem install neocities

      - name: Publicar StudyBox
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
        run: neocities push site
